### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by magnetophon** [swh/timemachine#5]
Packagers will rejoice!

**Comment by swh** [comment]
Can you check out https://github.com/swh/timemachine/releases/tag/v0.3.4 and see if it works.

I don't have a Linux system with working audio so can't test!

**Comment by magnetophon** [comment]
Sorry, I thought I replied to this already, but something went wrong apparently.

I tried this, and it worked, except that the first few seconds of each recording where silent.
Should I open a separate issue for that?

**Comment by swh** [comment]
That part of the codebase hasn't changed in a decade, so I doubt it's a bug?

How long is the time jump set for? Maybe you just didn't have signal at n seconds before you pressed record?

**Comment by magnetophon** [comment]
OK, so that shouldn't hold back a release then.
I won't have much time to test for a while, but will file a bug if I have any further troubles.

Thanks!
