### ISSUE TITLE
OSC messages not documented

### ISSUE THREAD

**Issue by riban-bw** [swh/timemachine#8]
The messages used to control timemachine via OSC are not documented. By looking at the source code and running some tests I believe there are two commands available (start / stop) which are triggered by sending an OSC message with the path `/start` or `/stop` and no arguments. 

Example Python code to test this:

```
import liblo
liblo.send(('localhost',7133), '/start')
liblo.send(('localhost',7133), '/stop')
```

It is simple but shouldn't require reading source code or empirical testing to figure it out :-). Maybe this could be added to the README.

**Comment by swh** [comment]
Thanks, good call, I'll add this to the README!
